apiVersion: apps/v1
kind: Deployment
metadata:
  name: voicevox
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: voicevox
  template:
    metadata:
      labels:
        app: voicevox
    spec:
      containers:
      - name: voicevox
        image: voicevox/voicevox_engine:cpu-latest
        ports:
        - containerPort: 50021